# Generated by Django 3.1.3 on 2025-07-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=50)),
                ('search_period', models.PositiveIntegerField(default=1)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
